### ISSUE TITLE
[REQUEST] Allow mkdocs-side global configuration

### ISSUE THREAD

**Issue by bczsalba** [bczsalba/mkdocs-termage-plugin#2]
**Is your feature request related to a problem? Please describe.**
It's a bit annoying having to set every configuration value on a per-codeblock basis. Also, it is currently not possible to change the 
output directory or naming scheme.

**Describe the solution you'd like**
Introduce `mkdocs` config options:

```yaml
plugins:
  - termage:
       output_dir: "docs/termage"
       output_name_template: "screenshot_{index}.svg"
       background: "#dddddd"
       foreground: "#212121"
```

**Describe alternatives you've considered**
Manual configuration, but it's very restrictive.
